# Generated by Django 6.0.4 on 2026-04-19 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('payment', 'Payment')], max_length=20)),
                ('merchant', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('atm', 'ATM'), ('pos', 'POS Terminal')], max_length=20)),
                ('transaction_time', models.IntegerField(help_text='Hour of transaction (0-23)')),
                ('status', models.CharField(choices=[('fraud', 'Fraud'), ('safe', 'Safe')], max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
